### ISSUE TITLE
extensions setting not working

### ISSUE THREAD

**Issue by droganov** [yobta/generator#33]
Сбилдил клиент и вижу:

<img width="998" alt="image" src="https://github.com/yobta/generator/assets/1375299/b6f4ea8f-c7ef-4f25-a9f3-d04c60386b81">

Расширения должны добавляться только если так указано в параметрах
если ничего не указано, расширения доблять не нужно

**Comment by droganov** [comment]
<img width="869" alt="image" src="https://github.com/yobta/generator/assets/1375299/ccd42335-9ad1-4d93-bcac-229c0611ea4e">

**Comment by droganov** [comment]
<img width="818" alt="image" src="https://github.com/yobta/generator/assets/1375299/5f2091bf-462a-474d-9153-b8d6f6a65ebf">

**Comment by droganov** [comment]
<img width="973" alt="image" src="https://github.com/yobta/generator/assets/1375299/f1bf966d-3e99-4457-b726-fb064867c132">

**Comment by plusbpm** [comment]
https://github.com/yobta/generator/pull/45
