### ISSUE TITLE
hooks build not worked

### ISSUE THREAD

**Issue by droganov** [yobta/generator#34]
<img width="1330" alt="image" src="https://github.com/yobta/generator/assets/1375299/74392b70-25ac-47b9-8510-192d23f19311">

В проекте нет гет запросов, бил прошел без ошибок, но его результат упорот.
если хуков нет, то либо не нужно ждобалять мертвый экспорт, либо нужно добавлять пустой файл хуков

сказанное верно для всех фабрик, выглядит так что ошибка будет воспроизводиться и для других фабрик

**Comment by plusbpm** [comment]
https://github.com/yobta/generator/pull/42
