### ISSUE TITLE
 flat exports

### ISSUE THREAD

**Issue by droganov** [yobta/generator#35]
Нужно сделать одномерный экспорт из front/generated/api/index.ts

## client
front/generated/api/client => front/generated/api/client.ts

## data-types
front/generated/api/data-types => front/generated/api/data-types.ts

## hooks
front/generated/api/hooks => front/generated/api/hooks.ts

## models
оставляем как есть

## routes
front/generated/api/routes => front/generated/api/routes.ts

к названиям переменных добавь пжс суффикс route
Было fetchExpenses
Стало fetchExpensesRoute

## server
front/generated/api/server => front/generated/api/server.ts
к названиям методов нужно добавлять префикс server

Было:
fetchUsers

Стало:
serverFetchUsers

Кроме того нужен параметр конфигурации аналогичный тому котрый отфильтровывает хуки по методу.
Здесь принцип тот же, серверу по-умолчанию нужны только гет методы, если иное не указано у конфигурации

У сервера и хуков свои настройки а не одна общая

**Comment by plusbpm** [comment]
https://github.com/yobta/generator/pull/46
