### ISSUE TITLE
add jsdoc to hooks

### ISSUE THREAD

**Issue by droganov** [yobta/generator#43]
У хуков нет jsDoc
<img width="1016" alt="image" src="https://github.com/yobta/generator/assets/1375299/9cb26854-0b41-4974-9dd3-8e5144d8c15a">

Нужно добавить по аналогии с методами
Кроме того дабывать разрыв строки между хуками чтобы отделить их друг от друга

**Comment by plusbpm** [comment]
https://github.com/yobta/generator/pull/47
